hbstack/header

assets/hb/modules/header/js/index.ts, assets/hb/modules/header/scss/_header.scss
=> style: hide/show the sticky header when scroll down/up

layouts/partials/hb/modules/header/menu.html
See https://github.com/hbstack/theme/issues/28
=> fix: set the dropdown toggle's `href` as `#`

modules/search/assets/hb/modules/hb-header-search/scss/index.scss
=> fix(search): remove the search icon's active color on hover

modules/docsearch/assets/hb/modules/hb-header-docsearch/scss/index.scss, modules/docsearch/go.mod, modules/docsearch/go.sum, modules/docsearch/hugo.toml, modules/docsearch/layouts/partials/hb/modules/header-docsearch/index.html, modules/docsearch/layouts/partials/hugopress/modules/hb-header-docsearch/hooks/body-end.html, modules/docsearch/layouts/partials/hugopress/modules/hb-header-docsearch/hooks/hb-header-togglers-begin.html, modules/docsearch/layouts/partials/hugopress/modules/hb-header-docsearch/hooks/head-end.html
=> feat: add the docsearch module

assets/hb/modules/header/scss/themes/_default.scss
=> fix: align brand and logo with menus

modules/search/assets/hb/modules/hb-header-search/scss/index.scss, modules/search/layouts/partials/hb/modules/header-search/index.html
=> fix(search): make search input clickable

hugo.toml, layouts/partials/hb/modules/header/brand.html
=> feat: add the brand_url for customizing brand URL

assets/hb/modules/header/scss/_header.scss, layouts/partials/hb/modules/header/submenu.html
=> style: show the full description of dropdown menus

.release-please-manifest.json, release-please-config.json, themes/pills/assets/hb/modules/header-theme/scss/index.scss, themes/pills/go.mod, themes/pills/go.sum, themes/pills/hugo.toml
=> feat: add the pills theme

modules/banner/assets/hb/modules/banner/scss/index.scss
=> fix(banner): correct the brand color

modules/banner/layouts/partials/hb/modules/header-banner/index.html
=> feat(banner): add the hb.header.banner parameters

modules/banner/assets/hb/modules/banner/scss/index.scss, modules/banner/layouts/partials/hb/modules/header-banner/index.html
=> feat(banner): add the color parameter

assets/hb/modules/header-theme/scss/index.scss, assets/hb/modules/header/scss/_header.scss, assets/hb/modules/header/scss/variables.tmpl.scss, hugo.toml, layouts/partials/hb/modules/header/functions/breakpoint.html, layouts/partials/hb/modules/header/index.html, layouts/partials/hb/modules/header/menu.html
Available options: `lg`, `xl`, `xxl`.
=> feat: add the breakpoint parameter that used for collapsing/expanding

assets/hb/modules/header/scss/_header.scss
=> feat: show two columns on dropdown menus on large screens

assets/hb/modules/header/scss/_header.scss, layouts/partials/hb/modules/header/menu.html
=> style: dropdown menu header takes full width

layouts/partials/hb/modules/header/submenu.html
=> feat: use the page description for dropdown menu if set

.prettierrc, .release-please-manifest.json, modules/gcse/assets/hb/modules/hb-header-gcse/scss/_input.scss, modules/gcse/assets/hb/modules/hb-header-gcse/scss/_reboot.scss, modules/gcse/assets/hb/modules/hb-header-gcse/scss/_result.scss, modules/gcse/assets/hb/modules/hb-header-gcse/scss/index.scss, modules/gcse/go.mod, modules/gcse/hugo.toml, modules/gcse/layouts/_default/gcse-standalone.html, modules/gcse/layouts/_default/gcse.html, modules/gcse/layouts/partials/hb/modules/header-gcse/assets/js.html, modules/gcse/layouts/partials/hb/modules/header-gcse/functions/layout.html, modules/gcse/layouts/partials/hb/modules/header-gcse/index.html, modules/gcse/layouts/partials/hugopress/modules/hb-header-gcse/hooks/body-end.html, modules/gcse/layouts/partials/hugopress/modules/hb-header-gcse/hooks/hb-header-togglers-begin.html, release-please-config.json
=> Add GCSE support

modules/news/hugo.toml, modules/news/layouts/partials/hb/modules/header-news/index.html
style(news): take full width on small screens
style(news): show the text next to icon on small screens
style(news): change the weight as 10
=> Tweak news styles

modules/news/hugo.toml, modules/news/layouts/partials/hb/modules/header-news/index.html
=> feat(news): add the icon_name and icon_vendor parameters

modules/theme-toggle/i18n/fr.toml
=> feat(i18n): add french translations for theme-toggle

modules/theme-toggle/assets/hb/modules/header-theme-toggle/init/index.ts, modules/theme-toggle/hugo.toml, modules/theme-toggle/layouts/partials/hb/modules/header-theme-toggle/index.html
Closes #398 
To use the dropdown style back.
```yaml
// params.yaml
hb:
header:
theme_toggle:
style: dropdown
```
=> feat(theme-toggle): add switch style and set it to default

modules/theme-toggle/layouts/partials/hb/modules/header-theme-toggle/index.html
=> fix(theme-toggle): replace <a> with <button>

modules/git-org/layouts/partials/hb/modules/header/modules/git-org/functions/data.html
=> perf(git-org): use GraphQL API for fetching stars count of multiple repos

modules/apps/assets/hb/modules/header-apps/scss/index.scss, modules/apps/go.mod, modules/apps/hugo.toml, modules/apps/i18n/en.toml, modules/apps/i18n/zh-hans.toml, modules/apps/i18n/zh-hant.toml, modules/apps/layouts/partials/hb/modules/header-apps/index.html, modules/apps/layouts/partials/hugopress/modules/hb-header-apps/hooks/hb-header-panel.html
=> feat(apps): first version

modules/banner/assets/hb/modules/banner/scss/index.scss, modules/banner/assets/hb/modules/banner/scss/variables.tmpl.scss, modules/banner/hugo.toml
Only works if transparentize_navbar_bg is false, default to 0.8.
=> feat(banner): add the hb.header.banner.navbar_opacity parameter

assets/hb/modules/header/js/index.ts, layouts/partials/hb/modules/header/index.html, layouts/partials/hb/modules/header/menu-name.html, layouts/partials/hb/modules/header/menu.html, layouts/partials/hb/modules/header/submenu.html, modules/language-picker/hugo.toml, modules/search/hugo.toml, modules/theme-toggle/hugo.toml
perf: use JavaScript to determind current active menu
Closes #599
=> perf: cache partials

layouts/partials/hb/modules/header/menu.html
=> feat: add the divider parameter for menu entry

assets/hb/modules/header/scss/_header.scss, layouts/partials/hb/modules/header/submenu.html
fix(menu): submenus alignments
=> fix(menu): submenus overflow

modules/language-picker/hugo.toml, modules/language-picker/layouts/partials/hb/modules/header-language-picker/index.html
=> feat(language-picker): use translation page if exists for current page
